# This is a basic workflow to help you get started with Actions

name: IntervalNetlifyWebHook

# このActionが実行されるイベント。今回は定期実行(schedule)と手動実行(workflow_dispatch)してほしいので
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Run a one-line script
      run: echo WebHook!
      
    - name: Github Action for curl
      uses: wei/curl@v1.1.1
      with:
        args: -X POST -d {} ${{ secrets.WEBHOOK_URL }}
