# This is a basic workflow to help you get started with Actions

name: CSVFileToJSONFile

# このActionが実行されるイベント。今回は定期実行(schedule)と手動実行(workflow_dispatch)してほしいので
on:
  workflow_dispatch:
  # schedule:
  #  - cron: 0 0 * * * # 日本時間で九時？

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # 環境
    runs-on: ubuntu-latest
        
    steps:
      # リポジトリに触れるように
      - uses: actions/checkout@v2

      # 必要なものを入れる
      - name: Node.js Start
        run: npm install
      
      # CSVファイルを落としてJSONファイルを作成するプログラム(download/main.js)を実行
      - name: CSVFileToJSON
        run: npm run download
    
      # コミットする
      - name: Git Setting
        run: |
          git config --global user.email "${{ secrets.MAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
                  
      # Pushする
      - name: Push JSON File
        run: |
           git commit -m "[GitHub Actions] JSON File Update" -a
           git pull
           git push origin master
